# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4236c4f1e3310cbf16691f4fcaf3b84df6d9f5c784f0b8f8c3a1967a7fd5eac6f3337cce0c8891950f9fa747e0a7d3d9616ae5036aece27015aa181ceb1a6401

test:
  secret_key_base: ec8b2c1ae5c817b446b38b57d9e16673d7b6ac1e06d57df55799607dcc8a2993cd1b11c03e848836ad8d0f484219cc40ae871d59233323a1007924edf4b03ab5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
